stages:
  - test
  - style

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

variables:
  GIT_DEPTH: 0

include:
  - 'https://gitlab.com/Cynerd/gitlab-ci-nix/-/raw/master/template.yml'

## Test stage ##################################################################

nix-check:
  stage: test
  extends: .nix
  script:
    - nix flake check

statix:
  stage: test
  extends: .nix
  script:
    - nix run .#statix -- check .

deadnix:
  stage: test
  extends: .nix
  allow_failure: true
  script:
    - nix run .#deadnix -- -f .

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

## Style stage #################################################################

nixfmt:
  stage: style
  extends: .nix
  allow_failure: true
  script:
    - nix fmt
    - git diff --exit-code
