stages:
  - test
  - style

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

variables:
  GIT_DEPTH: 0

.nix:
  image: registry.gitlab.com/cynerd/gitlab-ci-nix
  tags:
    - docker
  cache:
    key: "nix"
    paths:
      - ".nix-cache"
  before_script:
    - gitlab-ci-nix-cache-before
  after_script:
    - gitlab-ci-nix-cache-after


## Test stage ##################################################################

nix-check:
  stage: test
  extends: .nix
  script:
    - nix flake check

.template:
  extends: .nix
  script:
    - mkdir /tmp/test && cd /tmp/test
    - nix flake init --template "$CI_PROJECT_DIR"
    - nix run "$CI_PROJECT_DIR#gnused" -- -i "s|url = .*|url = \"$CI_PROJECT_DIR\";|" flake.nix

template-run:
  stage: test
  extends: .template
  script:
    - !reference [.template, script]
    - nix run . -- -r

template-nix-check:
  stage: test
  extends: .template
  script:
    - !reference [.template, script]
    - nix flake check -L

statix:
  stage: test
  extends: .nix
  script:
    - nix run .#statix -- check .

deadnix:
  stage: test
  extends: .nix
  allow_failure: true
  script:
    - nix run .#deadnix -- -f .

include:
  - template: Security/Secret-Detection.gitlab-ci.yml

## Style stage #################################################################

nixfmt:
  stage: style
  extends: .nix
  allow_failure: true
  script:
    - nix fmt -- --check .
